### ISSUE TITLE
Agent counts one request as two requests when using WSGIMiddleware

### ISSUE THREAD

**Issue by gaganpreet** [newrelic/newrelic-python-agent#514] opened 2022-04-08 16:06 UTC
**Description**

I recently tested a FastAPI app in production preserving the old Flask code behind [WSGIMiddleware](https://github.com/abersheeran/a2wsgi/).

Newrelic Agent double counts requests made to an endpoint behind the middleware (when only one was made).

This is a screenshot of the NewRelic dashboard right after I deployed. Once I rolled back, the graph shifted back to normal. There was no extra load (compared with Heroku metrics).

![Screenshot_20220407_142817](https://user-images.githubusercontent.com/815873/162477843-749455a9-8c0a-4f11-bdf6-938c19aefd18.png)

**Expected Behavior**

Request shouldn't have been double counted. Throughput didn't change (cross verified with Heroku).

**Steps to Reproduce**

Contents of `main.py`:

```python
import time
from a2wsgi import WSGIMiddleware
from fastapi import FastAPI
from flask import Flask

flask_app = Flask(__name__)


@flask_app.route("/flask_route")
def flask_route():
    time.sleep(2)
    return "Hello"


app = FastAPI()


@app.get("/fastapi_route")
def fastapi_route():
    time.sleep(2)
    return "Hello"


app.mount("/", WSGIMiddleware(flask_app))
```

I ran this script like this:

```bash
NEW_RELIC_CONFIG_FILE=newrelic.ini NEW_RELIC_AUDIT_LOG=/tmp/newrelic_audit.log NEW_RELIC_STARTUP_DEBUG=1 NEW_RELIC_LOG_LEVEL=debug newrelic-admin run-program uvicorn main:app  --reload  --port 5000

# In another terminal:

tail -f  /tmp/newrelic_audit.log | grep -i -e flask_route -e fastapi_route

# And in yet another terminal

curl http://localhost:5000/fastapi_route
curl http://localhost:5000/flask_route
```

Flask route behind WSGI middleware will be logged twice, but FastAPI route will only be logged once.

**Your Environment**

Python: 3.10.2

Python Packages:

fastapi==0.75.1
newrelic==7.10.0.175
starlette==0.17.1
uvicorn==0.17.6

**Comment by TimPansino** [comment] 2022-04-14 21:00
Hello,

We've taken a look at your issue. `a2wsgi` is an unsupported package, and the fact that the web requests for wrapped applications are done on a separate thread is the cause of the issue. When that happens the agent assumes it's a different web request. 

As a measure to prevent the FastAPI transactions from appearing when trying to hit any routes in the Flask app, you could add a simple ASGIMiddleware as a wrapper around the `a2wsgi.WSGIMiddleware`. All it would need to do is call ignore transaction.

```
from starlette.middleware.base import BaseHTTPMiddleware
from newrelic.agent import ignore_transaction

class IgnoreTransactionMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request, call_next):
        ignore_transaction()
        return await call_next(request)

app.mount("/", IgnoreTransactionMiddleware(WSGIMiddleware(flask_app)))
```

The real fix for this issue would be a feature request for us to support `a2wsgi` officially and add context propagation to it, but that obviously would take a much more time before it would be implemented, and the above should help you in the meantime.

Let me know if that doesn't fix your issue and I'm happy to reopen this. Feel free to open a separate feature request issue for support for `a2wsgi` if you'd like to see built in instrumentation and we'll consider it.

**Closed by TimPansino** 2022-04-14 21:00 UTC
Labels: bug, needs-triage
