### ISSUE TITLE
notice_error should work even if there is no exception

### ISSUE THREAD

**Issue by rittneje** [newrelic/newrelic-python-agent#325] opened 2021-08-19 20:16 UTC
We are using v6.8.0.163. We would like to be able to report errors to New Relic that happen outside of any exception being thrown. However, it seems that if you call `notice_error` when there is no "active" exception (so `sys.exc_info()` returns `(None, None, None)`), then no error is recorded at all.

**Comment by TimPansino** [comment] 2021-08-20 21:34
The `notice_error` API takes an `error=` kwarg as a tuple as provided by `sys.exc_info()`. It should contain the exception type, the exception instance, and a traceback. If you pass this tuple in outside of the context of an exception it should report to New Relic. 

Can you confirm if you're already doing this?

**Comment by rittneje** [comment] 2021-08-20 22:01
We are trying to report an error without there being a thrown exception. Consequently, we don't have anything to pass for the `error` parameter.

**Comment by TimPansino** [comment] 2021-08-20 22:12
We need to have an exception instance to report. One way of doing what you want would be the following.

```
try:
    raise RuntimeError("Oops")
except:
    notice_error()
```

Fairly painless, could be parameterized into a function and put somewhere if you want to use a oneliner inside your code.

**Comment by rittneje** [comment] 2021-08-20 22:16
Yes, that's effectively what we are doing now as a workaround. However, it is still surprising that `notice_error` silently does nothing in this situation, especially since the docs don't explicitly mention it. https://docs.newrelic.com/docs/agents/python-agent/python-agent-api/noticeerror-python-agent-api/

**Comment by TimPansino** [comment] 2021-08-20 22:39
We'll try to make in the docs more clear. Closing this issue then as this is intended behavior.

If you have anything else related to this you have questions on feel free to reach out to support who will be more than happy to help.

**Closed by TimPansino** 2021-08-20 22:39 UTC
